# Copyright (c) 2021, 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
---
name: 'Configure Kubectl for Oracle Container Engine for Kubernetes (OKE)'
description: >-
  Install and configure Kubectl for a specific Oracle Container Engine for Kubernetes
  (OKE) cluster
inputs:
  cluster:
    required: true
    description: The OCID of the target OKE cluster
  enablePrivateEndpoint:
    required: false
    description: Set to true to connect to a private Kubernetes API endpoint. Requires a self-hosted GitHub Runner.
    default: 'false'
branding:
  icon: 'circle'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/index.js'
